name: Env Info
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Runtime Info
      run: |
        pwd
        ls -al
        set | grep ^BASH
        which bash
        ls -l /bin/bash /bin/sh
        bash --version
        sh --version
